In [30]:
import pandas as pd
movies = pd.read_csv('dataset.csv')
movies

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

# View Top First 10 Movie List:

In [31]:
movies.head(10)

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
5,667257,Impossible Things,"Family,Drama",es,"Matilde is a woman who, after the death of her...",14.358,2021-06-17,8.6,255
6,129,Spirited Away,"Animation,Family,Fantasy",ja,"A young girl, Chihiro, becomes trapped in a st...",92.056,2001-07-20,8.5,13093
7,730154,Your Eyes Tell,"Romance,Drama",ja,"A tragic accident lead to Kaori's blindness, b...",51.345,2020-10-23,8.5,339
8,372754,Dou kyu sei – Classmates,"Romance,Animation",ja,"Rihito Sajo, an honor student with a perfect s...",14.285,2016-02-20,8.5,239
9,372058,Your Name.,"Romance,Animation,Drama",ja,High schoolers Mitsuha and Taki are complete s...,158.270,2016-08-26,8.5,8895

# View Info of the Dataset

In [32]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 10000 non-null  int64
 1   title              10000 non-null  object
 2   genre              9997 non-null   object
 3   original_language  10000 non-null  object
 4   overview           9987 non-null   object
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 703.2+ KB

# View Missing Value of Dataset

In [33]:
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

# Checking Columns of the Dataset

In [34]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

# Create new Data frame
### Feature Selection
    
   - in this project, I'll only be using 4 features:
       - id
       - title
       - genre
       - overview
   - for the 'genre' and 'overview', i'll be merging it later...

In [35]:
movies = movies[['id','title','genre','overview']]
movies

,id,title,genre,overview
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...
...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"Action,Science Fiction,War","During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...

# Merging the 'genre' and 'overview' feature and create new column

- this is important since I'm only be using content base filtering method/technique in my movie recommendation system

In [37]:


# create new column called 'tags' containing the data in the 'overview' & 'genre'
movies['tags'] = movies['genre']+movies['overview']
movies

C:\Users\cmcod\AppData\Local\Temp\ipykernel_12652\948360466.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['genre']+movies['overview']

,id,title,genre,overview,tags
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o...","Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...,"Drama,CrimeIn the continuing saga of the Corle..."
...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy","The story follows the adventures of Aang, a yo...","Action,Adventure,FantasyThe story follows the ..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",The sharks take bite out of the East Coast whe...,"Action,TV Movie,Science Fiction,Comedy,Adventu..."
9997,13995,Captain America,"Action,Science Fiction,War","During World War II, a brave, patriotic Americ...","Action,Science Fiction,WarDuring World War II,..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",A man named Farmer sets out to rescue his kidn...,"Adventure,Fantasy,Action,DramaA man named Farm..."
9999,455957,Domino,"Thriller,Action,Crime",Seeking justice for his partner’s murder by an...,"Thriller,Action,CrimeSeeking justice for his p..."

# Delete/Drop the 'overview' and 'genre' in our new dataset
- This is to avoid any redundancy in our data frame

In [38]:
new_data = movies.drop(columns = ['overview', 'genre'])
new_data

,id,title,tags
0,278,The Shawshank Redemption,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,CrimeIn the continuing saga of the Corle..."
...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,FantasyThe story follows the ..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventu..."
9997,13995,Captain America,"Action,Science Fiction,WarDuring World War II,..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,DramaA man named Farm..."
9999,455957,Domino,"Thriller,Action,CrimeSeeking justice for his p..."

# Applying the algorithm
- we need to convert our text into a vector

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=10000, stop_words='english')
cv

CountVectorizer(max_features=10000, stop_words='english')

In [40]:
vector = cv.fit_transform(new_data['tags'].values.astype('U')).toarray()
vector.shape
#Output will be 10000x10000 matrix

(10000, 10000)

# Using the Cosine Similarity Technique

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similarity = cosine_similarity(vector)

### Showing the Similarity Value of each row

In [45]:
similarity

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]])

# Accessing the Index no. and getting the distance using the similarity

In [46]:
distance = sorted(list(enumerate(similarity[2])), reverse = True, key = lambda vector:vector[1])
distance

[(2, 1.0000000000000002),
 (4, 0.41247895569215265),
 (2412, 0.28867513459481287),
 (4569, 0.28426762180748055),
 (9520, 0.27801921874276636),
 (7049, 0.2773500981126146),
 (1816, 0.27399831217559545),
 (6964, 0.26461887337857853),
 (4872, 0.26352313834736496),
 (747, 0.25724787771376323),
 (734, 0.251259453814803),
 (779, 0.251259453814803),
 (2272, 0.251259453814803),
 (330, 0.24999999999999997),
 (519, 0.24999999999999997),
 (8555, 0.24326681639992057),
 (892, 0.24283093212859136),
 (7419, 0.2405626121623441),
 (8341, 0.23947373603569988),
 (951, 0.2381448361039201),
 (1120, 0.23570226039551584),
 (6587, 0.23570226039551584),
 (1447, 0.2357022603955158),
 (153, 0.2333333333333333),
 (7910, 0.2333333333333333),
 (9245, 0.23112508176051214),
 (1926, 0.22941573387056174),
 (3548, 0.22941573387056174),
 (4380, 0.22941573387056174),
 (3742, 0.2253744679276044),
 (709, 0.22360679774997894),
 (3927, 0.22360679774997894),
 (5597, 0.22271770159368698),
 (8086, 0.22271770159368698),
 (1842, 0.22222222222222227),
 (2624, 0.2204792759220492),
 (3550, 0.22047927592204916),
 (4127, 0.21919864974047637),
 (250, 0.2182178902359924),
 (4449, 0.2182178902359924),
 (7258, 0.2182178902359924),
 (5010, 0.21821789023599236),
 (2115, 0.21516574145596756),
 (5954, 0.21516574145596756),
 (6565, 0.21516574145596756),
 (7356, 0.21516574145596756),
 (9216, 0.21516574145596756),
 (6862, 0.2135042050734495),
 (1611, 0.2132007163556104),
 (4885, 0.2132007163556104),
 (5502, 0.2132007163556104),
 (9212, 0.2130032168075646),
 (456, 0.21081851067789195),
 (945, 0.2095395190312374),
 (634, 0.20851441405707477),
 (9362, 0.20851441405707477),
 (9672, 0.20851441405707477),
 (821, 0.20833333333333331),
 (2174, 0.20833333333333331),
 (4491, 0.20833333333333331),
 (5100, 0.20833333333333331),
 (2717, 0.2080125735844609),
 (8570, 0.20604084592303354),
 (434, 0.20573779994945587),
 (1070, 0.20573779994945587),
 (1491, 0.2041241452319315),
 (1629, 0.20309059861498083),
 (3235, 0.20211302086361077),
 (4496, 0.20211302086361077),
 (7318, 0.20211302086361077),
 (8075, 0.20211302086361077),
 (5367, 0.20100756305184242),
 (5420, 0.20100756305184242),
 (5605, 0.20100756305184242),
 (1155, 0.20064308847628198),
 (4169, 0.1987615979999813),
 (6141, 0.1976934175396371),
 (1171, 0.19720265943665385),
 (5877, 0.19641855032959654),
 (8984, 0.19641855032959654),
 (9706, 0.19641855032959654),
 (5527, 0.19611613513818404),
 (233, 0.19245008972987526),
 (767, 0.19245008972987526),
 (1216, 0.19245008972987526),
 (1773, 0.19245008972987526),
 (2605, 0.19245008972987526),
 (7016, 0.19245008972987526),
 (4866, 0.19245008972987523),
 (495, 0.19179881852291683),
 (956, 0.1911797782254681),
 (2827, 0.1911797782254681),
 (4967, 0.1911797782254681),
 (867, 0.19047619047619047),
 (1343, 0.18925832465255626),
 (214, 0.1889822365046136),
 (1118, 0.1889822365046136),
 (4953, 0.1889822365046136),
 (8826, 0.1889822365046136),
 (8756, 0.18856180831641267),
 (5723, 0.18681617943926832),
 (6064, 0.18681617943926832),
 (135, 0.1868161794392683),
 (838, 0.18633899812498245),
 (1233, 0.18633899812498245),
 (1564, 0.18633899812498245),
 (2522, 0.18633899812498245),
 (5806, 0.18633899812498245),
 (9953, 0.18633899812498245),
 (2656, 0.18569533817705186),
 (3390, 0.18569533817705186),
 (5189, 0.18569533817705186),
 (58, 0.1849000654084097),
 (794, 0.1849000654084097),
 (1362, 0.1849000654084097),
 (5614, 0.1849000654084097),
 (8325, 0.1849000654084097),
 (2011, 0.18257418583505536),
 (3042, 0.18257418583505536),
 (4513, 0.18220272220337375),
 (748, 0.181848241863327),
 (2729, 0.181848241863327),
 (9503, 0.181848241863327),
 (6195, 0.1800205749557739),
 (1679, 0.17960530202677488),
 (4880, 0.17960530202677488),
 (5632, 0.17960530202677488),
 (876, 0.1781741612749496),
 (2913, 0.1781741612749496),
 (4296, 0.1781741612749496),
 (4981, 0.1781741612749496),
 (7015, 0.1781741612749496),
 (949, 0.17791499872137212),
 (263, 0.17766726362967533),
 (2509, 0.17766726362967533),
 (3611, 0.17766726362967533),
 (4064, 0.1767766952966369),
 (5062, 0.17677669529663687),
 (6936, 0.17677669529663687),
 (7985, 0.17677669529663687),
 (1087, 0.17588161767036212),
 (9633, 0.17407765595569785),
 (2066, 0.17391639824998364),
 (6601, 0.17376201171422898),
 (6974, 0.17376201171422898),
 (8047, 0.17376201171422898),
 (3762, 0.1735852146410985),
 (1598, 0.17213259316477406),
 (3315, 0.17213259316477406),
 (3349, 0.17213259316477406),
 (3481, 0.17213259316477406),
 (4940, 0.17213259316477406),
 (5466, 0.17213259316477406),
 (5559, 0.17213259316477406),
 (6788, 0.17213259316477406),
 (7744, 0.17213259316477406),
 (7259, 0.17201561551404665),
 (2421, 0.17149858514250882),
 (5119, 0.1714985851425088),
 (1127, 0.1701758234142103),
 (3692, 0.1701758234142103),
 (4122, 0.17010345435994292),
 (7589, 0.17010345435994292),
 (8239, 0.16984155512168936),
 (1206, 0.1690308509457033),
 (3509, 0.1690308509457033),
 (6162, 0.1690308509457033),
 (7302, 0.1690308509457033),
 (8351, 0.1690308509457033),
 (8774, 0.16839382851364088),
 (1037, 0.16666666666666666),
 (1039, 0.16666666666666666),
 (1485, 0.16666666666666666),
 (1634, 0.16666666666666666),
 (1834, 0.16666666666666666),
 (2059, 0.16666666666666666),
 (2069, 0.16666666666666666),
 (2202, 0.16666666666666666),
 (2813, 0.16666666666666666),
 (2879, 0.16666666666666666),
 (3070, 0.16666666666666666),
 (3670, 0.16666666666666666),
 (4209, 0.16666666666666666),
 (5834, 0.16666666666666666),
 (6023, 0.16666666666666666),
 (6080, 0.16666666666666666),
 (6741, 0.16666666666666666),
 (8049, 0.16666666666666666),
 (8326, 0.16666666666666666),
 (5307, 0.16537964611894462),
 (6528, 0.16537964611894462),
 (1310, 0.1649915822768611),
 (272, 0.16343011261515333),
 (1133, 0.16343011261515333),
 (3262, 0.16343011261515333),
 (4562, 0.16343011261515333),
 (5111, 0.16343011261515333),
 (7816, 0.16343011261515333),
 (8253, 0.16343011261515333),
 (2742, 0.16222142113076254),
 (1212, 0.16222142113076252),
 (187, 0.16169041669088863),
 (897, 0.16169041669088863),
 (3242, 0.16169041669088863),
 (3704, 0.16169041669088863),
 (5889, 0.16169041669088863),
 (6830, 0.16169041669088863),
 (7058, 0.16169041669088863),
 (7207, 0.16169041669088863),
 (7626, 0.16169041669088863),
 (793, 0.16037507477489604),
 (2110, 0.16037507477489604),
 (3756, 0.16037507477489604),
 (4848, 0.16037507477489604),
 (1801, 0.16025399127347054),
 (1918, 0.16012815380508713),
 (2255, 0.16012815380508713),
 (3892, 0.16012815380508713),
 (4765, 0.16012815380508713),
 (5251, 0.16012815380508713),
 (5331, 0.16012815380508713),
 (6075, 0.1601281538050871),
 (6308, 0.1601281538050871),
 (393, 0.15811388300841897),
 (518, 0.15811388300841897),
 (2444, 0.15811388300841897),
 (2528, 0.15811388300841897),
 (3227, 0.15811388300841897),
 (7116, 0.15811388300841897),
 (7499, 0.15811388300841897),
 (3344, 0.15748519708717798),
 (7284, 0.15748519708717798),
 (7622, 0.15748519708717798),
 (3367, 0.15731330124142312),
 (105, 0.15713484026367724),
 (448, 0.15713484026367724),
 (1014, 0.15713484026367724),
 (1105, 0.15713484026367724),
 (1831, 0.15713484026367724),
 (2330, 0.15713484026367724),
 (3641, 0.15713484026367724),
 (4518, 0.15713484026367724),
 (4712, 0.15713484026367724),
 (6459, 0.15713484026367724),
 (7280, 0.15713484026367724),
 (7783, 0.15713484026367724),
 (8285, 0.15713484026367724),
 (8819, 0.15713484026367724),
 (9437, 0.15713484026367724),
 (3659, 0.15617376188860607),
 (850, 0.15474611514754322),
 (9034, 0.15474611514754322),
 (741, 0.1543033499620919),
 (2440, 0.1543033499620919),
 (5871, 0.1543033499620919),
 (1154, 0.15294382258037448),
 (1540, 0.15294382258037448),
 (1778, 0.15294382258037448),
 (2161, 0.15294382258037448),
 (2261, 0.15294382258037448),
 (3671, 0.15294382258037448),
 (4117, 0.15294382258037448),
 (4707, 0.15294382258037448),
 (4758, 0.15294382258037448),
 (5239, 0.15294382258037448),
 (5525, 0.15294382258037448),
 (7586, 0.15294382258037448),
 (8174, 0.15294382258037448),
 (8503, 0.15294382258037448),
 (8632, 0.15294382258037448),
 (8777, 0.15294382258037448),
 (9756, 0.15294382258037448),
 (1714, 0.15214515486254612),
 (2998, 0.15214515486254612),
 (3803, 0.15214515486254612),
 (4546, 0.15214515486254612),
 (5318, 0.15214515486254612),
 (9075, 0.15214515486254612),
 (190, 0.15075567228888181),
 (463, 0.15075567228888181),
 (469, 0.15075567228888181),
 (1482, 0.15075567228888181),
 (1533, 0.15075567228888181),
 (1636, 0.15075567228888181),
 (1988, 0.15075567228888181),
 (2483, 0.15075567228888181),
 (2553, 0.15075567228888181),
 (2626, 0.15075567228888181),
 (2839, 0.15075567228888181),
 (2856, 0.15075567228888181),
 (3872, 0.15075567228888181),
 (4567, 0.15075567228888181),
 (5625, 0.15075567228888181),
 (6257, 0.15075567228888181),
 (6432, 0.15075567228888181),
 (2554, 0.1496710850223124),
 (2872, 0.1496710850223124),
 (5811, 0.14907119849998599),
 (6, 0.14907119849998596),
 (92, 0.14907119849998596),
 (864, 0.14907119849998596),
 (1619, 0.14907119849998596),
 (1752, 0.14907119849998596),
 (2200, 0.14907119849998596),
 (3009, 0.14907119849998596),
 (3844, 0.14907119849998596),
 (4302, 0.14907119849998596),
 (4767, 0.14907119849998596),
 (5052, 0.14907119849998596),
 (5913, 0.14907119849998596),
 (5952, 0.14907119849998596),
 (6073, 0.14907119849998596),
 (6239, 0.14907119849998596),
 (7411, 0.14907119849998596),
 (8065, 0.14907119849998596),
 (8771, 0.14907119849998596),
 (9664, 0.14907119849998596),
 (3033, 0.14744195615489714),
 (25, 0.14731391274719738),
 (282, 0.14731391274719738),
 (1921, 0.14731391274719738),
 (7878, 0.14731391274719738),
 (9162, 0.14731391274719738),
 (7677, 0.14586499149789456),
 (710, 0.14547859349066158),
 (1034, 0.14547859349066158),
 (1480, 0.14547859349066158),
 (2731, 0.14547859349066158),
 (4394, 0.14547859349066158),
 (4493, 0.14547859349066158),
 (5574, 0.14547859349066158),
 (6481, 0.14547859349066158),
 (7247, 0.14547859349066158),
 (8242, 0.14547859349066158),
 (8935, 0.14547859349066158),
 (718, 0.14506471329641488),
 (3151, 0.14506471329641488),
 (5097, 0.14506471329641488),
 (6028, 0.14462030521243746),
 (9112, 0.14462030521243743),
 (1454, 0.14433756729740643),
 (1691, 0.14433756729740643),
 (1716, 0.14433756729740643),
 (2359, 0.14433756729740643),
 (2616, 0.14433756729740643),
 (2749, 0.14433756729740643),
 (2907, 0.14433756729740643),
 (3298, 0.14433756729740643),
 (3433, 0.14433756729740643),
 (4068, 0.14433756729740643),
 (4811, 0.14433756729740643),
 (4924, 0.14433756729740643),
 (4988, 0.14433756729740643),
 (5276, 0.14433756729740643),
 (5839, 0.14433756729740643),
 (5995, 0.14433756729740643),
 (6630, 0.14433756729740643),
 (6990, 0.14433756729740643),
 (7543, 0.14433756729740643),
 (8715, 0.14433756729740643),
 (8729, 0.14433756729740643),
 (8951, 0.14433756729740643),
 (9330, 0.14433756729740643),
 (9595, 0.14433756729740643),
 (279, 0.14291548761875733),
 (726, 0.14291548761875733),
 (1422, 0.14291548761875733),
 (4201, 0.14291548761875733),
 (8008, 0.14291548761875733),
 (4936, 0.14285714285714285),
 (789, 0.14213381090374028),
 (1189, 0.14213381090374028),
 (1244, 0.14213381090374028),
 (1817, 0.14213381090374028),
 (1908, 0.14213381090374028),
 (2124, 0.14213381090374028),
 (2394, 0.14213381090374028),
 (3727, 0.14213381090374028),
 (3749, 0.14213381090374028),
 (3857, 0.14213381090374028),
 (6096, 0.14213381090374028),
 (8427, 0.14213381090374028),
 (168, 0.14085904245475275),
 (441, 0.14085904245475275),
 (1354, 0.14085904245475275),
 (3656, 0.14085904245475275),
 (3709, 0.14085904245475275),
 (7461, 0.14085904245475275),
 (7937, 0.14085904245475275),
 (145, 0.1404501619333974),
 (7850, 0.14002800840280097),
 (933, 0.13900960937138318),
 (960, 0.13900960937138318),
 (1266, 0.13900960937138318),
 (1804, 0.13900960937138318),
 (2254, 0.13900960937138318),
 (2825, 0.13900960937138318),
 (3028, 0.13900960937138318),
 (4034, 0.13900960937138318),
 (4440, 0.13900960937138318),
 (4762, 0.13900960937138318),
 (6726, 0.13900960937138318),
 (6941, 0.13900960937138318),
 (7286, 0.13900960937138318),
 (7823, 0.13900960937138318),
 (572, 0.1388888888888889),
 (780, 0.1388888888888889),
 (6243, 0.1388888888888889),
 (1223, 0.1386750490563073),
 (2109, 0.1386750490563073),
 (2175, 0.1386750490563073),
 (2229, 0.1386750490563073),
 (2432, 0.1386750490563073),
 (2833, 0.1386750490563073),
 (2900, 0.1386750490563073),
 (3003, 0.1386750490563073),
 (3098, 0.1386750490563073),
 (3306, 0.1386750490563073),
 (3804, 0.1386750490563073),
 (4388, 0.1386750490563073),
 (4574, 0.1386750490563073),
 (4739, 0.1386750490563073),
 (5025, 0.1386750490563073),
 (5231, 0.1386750490563073),
 (5474, 0.1386750490563073),
 (6482, 0.1386750490563073),
 (6517, 0.1386750490563073),
 (7450, 0.1386750490563073),
 (8162, 0.1386750490563073),
 (8299, 0.1386750490563073),
 (8824, 0.1386750490563073),
 (9145, 0.1386750490563073),
 (3987, 0.13699915608779772),
 (4947, 0.13699915608779772),
 (5288, 0.13699915608779772),
 (5428, 0.13699915608779772),
 (6538, 0.13699915608779772),
 (7913, 0.13699915608779772),
 (8483, 0.13699915608779772),
 (9130, 0.13699915608779772),
 (210, 0.13608276348795434),
 (1265, 0.13608276348795434),
 (1331, 0.13608276348795434),
 (2267, 0.13608276348795434),
 (2274, 0.13608276348795434),
 (2644, 0.13608276348795434),
 (4549, 0.13608276348795434),
 (4806, 0.13608276348795434),
 (5081, 0.13608276348795434),
 (5908, 0.13608276348795434),
 (6405, 0.13608276348795434),
 (7688, 0.13608276348795434),
 (8992, 0.13608276348795434),
 (9149, 0.13608276348795434),
 (9189, 0.13608276348795434),
 (9718, 0.13608276348795434),
 (912, 0.13518451760896877),
 (1135, 0.13518451760896877),
 (1755, 0.13518451760896877),
 (3979, 0.13518451760896877),
 (7324, 0.13518451760896877),
 (5415, 0.13483997249264842),
 (9363, 0.13483997249264842),
 (331, 0.1336306209562122),
 (389, 0.1336306209562122),
 (1043, 0.1336306209562122),
 (1209, 0.1336306209562122),
 (1330, 0.1336306209562122),
 (1516, 0.1336306209562122),
 (1729, 0.1336306209562122),
 (1942, 0.1336306209562122),
 (2332, 0.1336306209562122),
 (2464, 0.1336306209562122),
 (2476, 0.1336306209562122),
 (2587, 0.1336306209562122),
 (2792, 0.1336306209562122),
 (3095, 0.1336306209562122),
 (3506, 0.1336306209562122),
 (3588, 0.1336306209562122),
 (3795, 0.1336306209562122),
 (3831, 0.1336306209562122),
 (4002, 0.1336306209562122),
 (4214, 0.1336306209562122),
 (4227, 0.1336306209562122),
 (4724, 0.1336306209562122),
 (5678, 0.1336306209562122),
 (6497, 0.1336306209562122),
 (6819, 0.1336306209562122),
 (6842, 0.1336306209562122),
 (7789, 0.1336306209562122),
 (8211, 0.1336306209562122),
 (8468, 0.1336306209562122),
 (8643, 0.1336306209562122),
 (8987, 0.1336306209562122),
 (9154, 0.1336306209562122),
 (9156, 0.1336306209562122),
 (9224, 0.1336306209562122),
 (9388, 0.1336306209562122),
 (9556, 0.1336306209562122),
 (9810, 0.1336306209562122),
 (9880, 0.1336306209562122),
 (3224, 0.13344012817090595),
 (3385, 0.13344012817090595),
 (4462, 0.13344012817090595),
 (7961, 0.13344012817090595),
 (8607, 0.13344012817090595),
 (1103, 0.13333333333333333),
 (2351, 0.13333333333333333),
 (3590, 0.13333333333333333),
 (4442, 0.13333333333333333),
 (5510, 0.13333333333333333),
 (5816, 0.13333333333333333),
 (5965, 0.13333333333333333),
 (7230, 0.13333333333333333),
 (8747, 0.13333333333333333),
 (9930, 0.13333333333333333),
 (612, 0.1329540058695776),
 (8519, 0.13245323570650439),
 (9279, 0.13209898731686948),
 (65, 0.13176156917368248),
 (1723, 0.13176156917368248),
 (2185, 0.13176156917368248),
 (2449, 0.13176156917368248),
 (4840, 0.13176156917368248),
 (5638, 0.13176156917368248),
 (6751, 0.13176156917368248),
 (7267, 0.13176156917368248),
 (9858, 0.13176156917368248),
 (121, 0.13130643285972254),
 (230, 0.13130643285972254),
 (70, 0.13074409009212268),
 (693, 0.13074409009212268),
 (4343, 0.13074409009212268),
 (5635, 0.13074409009212268),
 (6778, 0.13074409009212268),
 (7136, 0.13074409009212268),
 (8069, 0.13074409009212268),
 (8189, 0.13074409009212268),
 (8569, 0.13074409009212268),
 (8675, 0.13074409009212268),
 (9349, 0.13074409009212268),
 (7437, 0.13018891098082389),
 (1951, 0.1301448015738384),
 (2051, 0.1301448015738384),
 (2654, 0.1301448015738384),
 (2580, 0.12962962962962962),
 (37, 0.12909944487358055),
 (90, 0.12909944487358055),
 (440, 0.12909944487358055),
 (948, 0.12909944487358055),
 (1427, 0.12909944487358055),
 (2004, 0.12909944487358055),
 (2120, 0.12909944487358055),
 (2533, 0.12909944487358055),
 (2977, 0.12909944487358055),
 (3212, 0.12909944487358055),
 (3826, 0.12909944487358055),
 (3955, 0.12909944487358055),
 (4006, 0.12909944487358055),
 (4326, 0.12909944487358055),
 (5030, 0.12909944487358055),
 (5238, 0.12909944487358055),
 (5443, 0.12909944487358055),
 (6253, 0.12909944487358055),
 (6286, 0.12909944487358055),
 (6305, 0.12909944487358055),
 (6563, 0.12909944487358055),
 (6708, 0.12909944487358055),
 (7465, 0.12909944487358055),
 (7588, 0.12909944487358055),
 (7866, 0.12909944487358055),
 (8043, 0.12909944487358055),
 (8112, 0.12909944487358055),
 (8398, 0.12909944487358055),
 (8830, 0.12909944487358055),
 (8961, 0.12909944487358055),
 (9081, 0.12909944487358055),
 (9469, 0.12909944487358055),
 (9936, 0.12909944487358055),
 (15, 0.12858612496840993),
 (671, 0.12858612496840993),
 (2298, 0.12858612496840993),
 (2302, 0.12830005981991682),
 (2463, 0.12830005981991682),
 (2882, 0.12830005981991682),
 (3046, 0.12830005981991682),
 (3881, 0.12830005981991682),
 (4756, 0.12830005981991682),
 (5175, 0.12830005981991682),
 (6184, 0.12830005981991682),
 (7071, 0.12830005981991682),
 (7762, 0.12830005981991682),
 (8071, 0.12830005981991682),
 (9921, 0.1270821419438372),
 (5060, 0.1270001270001905),
 (482, 0.1259881576697424),
 (1068, 0.1259881576697424),
 (2529, 0.1259881576697424),
 (2550, 0.1259881576697424),
 (2894, 0.1259881576697424),
 (3233, 0.1259881576697424),
 (4757, 0.1259881576697424),
 (4884, 0.1259881576697424),
 (5893, 0.1259881576697424),
 (7043, 0.1259881576697424),
 (7684, 0.1259881576697424),
 (9035, 0.1259881576697424),
 (3020, 0.1256297269074015),
 (6172, 0.1256297269074015),
 (253, 0.125),
 (346, 0.125),
 (797, 0.125),
 (894, 0.125),
 (1017, 0.125),
 (1138, 0.125),
 (1309, 0.125),
 (1878, 0.125),
 (1974, 0.125),
 (2015, 0.125),
 (2103, 0.125),
 (2290, 0.125),
 (2719, 0.125),
 (2937, 0.125),
 (3196, 0.125),
 (3280, 0.125),
 (3523, 0.125),
 (3674, 0.125),
 (3843, 0.125),
 (4101, 0.125),
 (4221, 0.125),
 (4842, 0.125),
 (5517, 0.125),
 (6070, 0.125),
 (6122, 0.125),
 (6229, 0.125),
 (6346, 0.125),
 (6683, 0.125),
 (6815, 0.125),
 (7244, 0.125),
 (7314, 0.125),
 (7986, 0.125),
 (8025, 0.125),
 (8674, 0.125),
 (9007, 0.125),
 (9292, 0.125),
 (9599, 0.125),
 (9643, 0.125),
 (9673, 0.125),
 (9707, 0.125),
 (5587, 0.12422599874998833),
 (8355, 0.1242259987499883),
 (208, 0.12379689211803457),
 (1230, 0.12379689211803457),
 (3314, 0.12379689211803457),
 (3664, 0.12379689211803457),
 (4720, 0.12379689211803457),
 (8685, 0.12366641933407534),
 (609, 0.1228682967957476),
 (2218, 0.1228682967957476),
 (3849, 0.1228682967957476),
 (5321, 0.12216944435630521),
 (2583, 0.1217161238900369),
 (3471, 0.1217161238900369),
 (4699, 0.1217161238900369),
 (4845, 0.1217161238900369),
 (6339, 0.1217161238900369),
 (6472, 0.1217161238900369),
 (7942, 0.1217161238900369),
 (9102, 0.1217161238900369),
 (26, 0.12126781251816647),
 (126, 0.12126781251816647),
 (276, 0.12126781251816647),
 (1094, 0.12126781251816647),
 (1875, 0.12126781251816647),
 (2142, 0.12126781251816647),
 (2470, 0.12126781251816647),
 (2788, 0.12126781251816647),
 (2946, 0.12126781251816647),
 (3355, 0.12126781251816647),
 (3426, 0.12126781251816647),
 (3554, 0.12126781251816647),
 (3587, 0.12126781251816647),
 (3595, 0.12126781251816647),
 (3777, 0.12126781251816647),
 (4052, 0.12126781251816647),
 (4056, 0.12126781251816647),
 (4864, 0.12126781251816647),
 (5290, 0.12126781251816647),
 (5586, 0.12126781251816647),
 (5961, 0.12126781251816647),
 (6030, 0.12126781251816647),
 (6275, 0.12126781251816647),
 (6327, 0.12126781251816647),
 (6499, 0.12126781251816647),

# Accessing the first 5 closest similarity

In [48]:
#Except from the first index get the first 5 closest similarity
for i in distance[1:6]:
    print(new_data.iloc[i[0]].title)

The Godfather: Part II
Felon
House of Gucci
Gotti
The Outsider

In [51]:
#create a function to test if the algorithm works
def recommend(movies):
    index = new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse = True, key = lambda vector:vector[1])
    for i in distance[1:6]:
        print(new_data.iloc[i[0]].title)

In [61]:
#pass some data in the function
recommend("Barbie of Swan Lake")

Snow White and the Huntsman
The Swan Princess
Bambi II
The Swan Princess: The Mystery of the Enchanted Kingdom
Barbie Fairytopia: Magic of the Rainbow

# Saving into a pickle file

In [56]:
import pickle

In [57]:
pickle.dump(new_data,open('movies_list.pkl','wb'))

In [58]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [59]:
# opening the file
pickle.load(open('movies_list.pkl','rb'))

,id,title,tags
0,278,The Shawshank Redemption,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,CrimeIn the continuing saga of the Corle..."
...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,FantasyThe story follows the ..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventu..."
9997,13995,Captain America,"Action,Science Fiction,WarDuring World War II,..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,DramaA man named Farm..."
9999,455957,Domino,"Thriller,Action,CrimeSeeking justice for his p..."

In [60]:
# opening the file
pickle.load(open('similarity.pkl','rb'))

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03798686],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03327792],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04761905],
       [0.03798686, 0.        , 0.        , ..., 0.03327792, 0.04761905,
        1.        ]])